import{Router}from'express';import{join,dirname}from'path';import{existsSync,mkdirSync,rmSync,writeFileSync,readFileSync}from'fs';import{fileURLToPath}from'url';import{v4}from'uuid';import{downloadCrx,extractIdFromUrl}from'../services/crxDownloader.js';import{unpackCrxBuffer,readLocalExtension}from'../services/crxUnpacker.js';import{scanAllLocalExtensions}from'../services/localScanner.js';
const r=Router();const __dirname=dirname(fileURLToPath(import.meta.url));const STORE=join(__dirname,'..','store');if(!existsSync(STORE))mkdirSync(STORE,{recursive:true});
const s=new Map();
setInterval(()=>{const n=Date.now();for(const[id,session]of s){if(n-session.createdAt>3600000){try{rmSync(join(STORE,id),{recursive:true,force:true})}catch{}s.delete(id)}}},300000);
function saveSession(files,manifest){const id=v4();s.set(id,{files,manifest,createdAt:Date.now()});const d=join(STORE,id);mkdirSync(d,{recursive:true});for(const f of files){const fp=join(d,f.path);const dir=join(d,f.path.split('/').slice(0,-1).join('/'));if(!existsSync(dir))mkdirSync(dir,{recursive:true});writeFileSync(fp,f.content)}return id;}
function tree(files){const t={};for(const f of files){const p=f.path.split('/');let n=t;for(let i=0;i<p.length;i++){if(i===p.length-1)n[p[i]]={__file:true,path:f.path,size:f.size};else{if(!n[p[i]])n[p[i]]={};n=n[p[i]];}}}return t;}
r.post('/from-url',async(req,res)=>{try{const{url,proxy}=req.body;if(!url)return res.status(400).json({error:'缺少url'});const{id,store}=extractIdFromUrl(url);const buf=await downloadCrx(id,store,proxy);const{files,manifest}=unpackCrxBuffer(buf);const sid=saveSession(files,manifest);res.json({sessionId:sid,id,store,name:manifest?.name,version:manifest?.version,fileTree:tree(files),fileCount:files.length})}catch(err){res.status(500).json({error:err.message})}});
r.post('/from-id',async(req,res)=>{try{const{id,store='chrome',proxy}=req.body;if(!id)return res.status(400).json({error:'缺少id'});const buf=await downloadCrx(id,store,proxy);const{files,manifest}=unpackCrxBuffer(buf);const sid=saveSession(files,manifest);res.json({sessionId:sid,id,store,name:manifest?.name,version:manifest?.version,fileTree:tree(files),fileCount:files.length})}catch(err){res.status(500).json({error:err.message})}});
r.get('/local',(_req,res)=>{try{res.json({extensions:scanAllLocalExtensions()})}catch(err){res.status(500).json({error:err.message})}});
r.post('/from-local',(req,res)=>{try{const{path}=req.body;if(!path)return res.status(400).json({error:'缺少path'});const{files,manifest}=readLocalExtension(path);const sid=saveSession(files,manifest);res.json({sessionId:sid,name:manifest?.name,version:manifest?.version,fileTree:tree(files),fileCount:files.length})}catch(err){res.status(500).json({error:err.message})}});
r.get('/:sid/file',(req,res)=>{try{const{sid}=req.params;const fp=req.query.path;const session=s.get(sid);if(!session)return res.status(404).json({error:'过期'});if(!fp)return res.json({files:session.files.map(f=>({path:f.path,size:f.size}))});const f=session.files.find(x=>x.path===fp);if(!f)return res.status(404).json({error:'不存在'});res.json({path:f.path,content:f.content,size:f.size})}catch(err){res.status(500).json({error:err.message})}});
r.get('/:sid/download',async(req,res)=>{try{const{sid}=req.params;const session=s.get(sid);if(!session)return res.status(404).json({error:'过期'});const{default:Zip}=await import('adm-zip');const z=new Zip();for(const f of session.files)z.addFile(f.path,Buffer.from(f.content,'utf-8'));const b=z.toBuffer();const n=`${session.manifest?.name||'ext'}-${sid.slice(0,8)}.zip`;res.set({'Content-Type':'application/zip','Content-Disposition':`attachment; filename="${n}"`,'Content-Length':b.length});res.send(b)}catch(err){res.status(500).json({error:err.message})}});
r.get('/:sid/manifest',(req,res)=>{try{const{sid}=req.params;const session=s.get(sid);if(!session)return res.status(404).json({error:'过期'});res.json(session.manifest||{})}catch(err){res.status(500).json({error:err.message})}});
export{r as extensionsRouter};
